# Changes relative to https://github.com/sds/overcommit/blob/master/config/default.yml
PreCommit:
  ForbiddenBranches:
    enabled: true
    description: Don't commit to master
    branch_patterns: ['master']

  Scalastyle:
    enabled: true
    flags: ['-w', 'true', '-c', './project/scalastyle_config.xml', 'src']

  # brew install --HEAD olafurpg/scalafmt/scalafmt
  CustomScript:
    enabled: true
    required_executable: 'scalafmt'
    flags: ['-c', '.scalafmt.conf', 'src'] 

  JsonSyntax:
    enabled: true

  TravisLint:
    enabled: true

  XmlSyntax:
    enabled: true

  YamlSyntax:
    enabled: true
